version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://opsshield:opsshield@db:5432/opsshield
      PRISMA_QUERY_ENGINE_LIBRARY: /app/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node
      PRISMA_SCHEMA_ENGINE_BINARY: /app/node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      PAYSTACK_SECRET_KEY: ${PAYSTACK_SECRET_KEY}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3001}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:3001}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: ${SMTP_FROM}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./public:/app/public
      - /app/node_modules

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: opsshield
      POSTGRES_USER: opsshield
      POSTGRES_PASSWORD: opsshield
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U opsshield"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
